### ISSUE TITLE
can't craft non vanilla tool heads

### ISSUE THREAD

**Issue by HarroldSaxon** [alcatrazEscapee/tinkers-forging#10]
I'm using tinkers to register materials, but with the tools module dissabled. The hammer head for each material is craftable, but all other generated tool heads are not.
 I've made recipes to craft tools from embers with craft tweaker that use your tool heads, but can't make the actual tool heads. :(
Could you please add these recipes, or add some form of custom recipe support? 

Thank you so so much for this mod! I've been wishing for a crafting system like this<3

**Comment by alcatrazEscapee** [comment]
Anvil recipes for Tinker's Forging tools will register automatically if you set `"Tinker's Construct Compat" = false` in the config. If you want you can add recipes via craft tweaker, but they should be able to be added automatically.

**Comment by HarroldSaxon** [comment]
"Tinker's Construct Compat" is set false, but I can not craft the copper pickaxe head in your anvil. I'lk take a screenshot once I get home tonight.

**Comment by alcatrazEscapee** [comment]
I think I might of found the issue. A couple questions:
1) Do the normal vanilla materials work? (i.e. iron, gold)
2) If no, have you disabled the vanilla tool recipes / items somehow? (i.e. with this or another mod's config)

**Comment by HarroldSaxon** [comment]
The vanilla materials are working fine. I put hot iron in your anvil and the buttons all work, recipe pops right up. any non vanilla ingot and no such luck.

**Comment by HarroldSaxon** [comment]
![20190110_220440](https://user-images.githubusercontent.com/16321509/51012710-2b3dff00-1524-11e9-8abd-0bba43213910.jpg)
![20190110_220549](https://user-images.githubusercontent.com/16321509/51012714-32650d00-1524-11e9-9b17-748ffccbd4ec.jpg)

**Comment by alcatrazEscapee** [comment]
Ok, I think I know what's going on. I'll try and fix that this weekend.

**Comment by alcatrazEscapee** [comment]
Should be fixed in 1.0.5. If not let me know.

**Comment by HarroldSaxon** [comment]
it part way fixed it. Thaumcraft brass now works, as do ardite, cobalt, pig iron, etc. However, using ingots from Enbers still isn't working. The ingots can heat, and the corresponding tool heads are in the creative menu, but I still can't make them in the anvil.

**Comment by alcatrazEscapee** [comment]
Well that's annoying. What materials aren't working? Are they registered as "ingot..." in the ore dictionary?

**Comment by HarroldSaxon** [comment]
I'm at work right now, but the ones i remember are copper, tin, bronze, silver, and electrum. I'll double chec the ore dict after work.

**Comment by alcatrazEscapee** [comment]
Ok I think I found the issue (again). Ember's doesn't register it's items to the ore dict until after the recipe register event has passed. I cannot fix this easily, nor can I add better metal detection without a serious rewrite of the mod, which I simply don't have time to do. So I am providing a cheeky fix: a new config option `Force Enabled Materials`, which you can add the material names (i.e. "copper", "tin", etc.) to there.

Or add the recipes manually via craft tweaker. Because there are still some things that might slip by.

**Comment by alcatrazEscapee** [comment]
Should be fixed in 1.0.6. If not then force them via config :P

**Comment by HarroldSaxon** [comment]
Thank you so much for all your help!
